[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "easyxrd"
version = "2026.09.20"
description = "X-ray diffraction analysis tool"
readme = "README.md"
requires-python = ">=3.11"
license = {file = "LICENSE"}
authors = [{name = "Mehmet Topsakal"}]
dependencies = [
    "numpy", "scipy", "xarray", "matplotlib", "ipython",
    "pymatgen", "pyFAI", "fabio", "pybaselines", "h5netcdf", "h5py", "mp-api"
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3 :: Only",
]

[project.optional-dependencies]
notebook = ["jupyterlab", "ipympl", "ipywidgets"]

[project.urls]
Homepage = "https://github.com/MehmetTopsakal/easyXRD"

[tool.setuptools]
packages = ["easyxrd"]
